name: Build-Inputer

on:
  push:
    paths:
    - '**.py'
    - '**.yml'
  pull_request:
    paths:
    - '**.py'
    - '**.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies & Copy library
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          mkdir -p ./dist/Lib/
          cp ./Lib/opencv_face_detector_uint8.pb ./dist/Lib/
          cp ./Lib/opencv_face_detector.pbtxt ./dist/Lib/

    - name: Build For Windows/Mac/Linux
      run: |
          pyinstaller -F 'Gfriends Inputer.py' --collect-all grapheme

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Gfriends-Inputer-${{ runner.os }}
        path: dist
